### ISSUE TITLE
Портировать контроллер path_follower из ROS1 в ROS2 

### ISSUE THREAD

**Issue by urock** [FastSense/rosbot-ros2#7]
Источник
https://github.com/urock/rosbot/blob/develop/rosbot_controller/src/path_follower.py

Портировать сюда
https://github.com/FastSense/rosbot-ros2/tree/master/rosbot_controller/rosbot_controller

Примеры как запускать контроллер в ROS1 покажет @KostyaYamshanov 
Кость, скинь сюда примеры запуска и помогай с портированием кода

**Comment by CI314X** [comment]
8 пункт выполнен, ждет проверки от @KostyaYamshanov
Комментарии: 1. код внутри path_publisher обернут в класс
                         2. к path_follower и к path_publisher написана короткая документация
                         3.  в rosbot_controller/README.md описана инструкция по запуску

**Comment by CI314X** [comment]
Комментарии по 8 пункту:
1. Удалена функция euler_to_quaternion.
2. Убраны лишние prints, добавлены LaunchDescriptions
3. rosbot.py переименован в rosbot_2D.
