### ISSUE TITLE
Портировать Model runner из ROS-1 в ROS-2

### ISSUE THREAD

**Issue by KostyaYamshanov** [FastSense/rosbot-ros2#8]
Нужно портировать ноду model_runner из ROS-1 в ROS-2

Суть ноды model_runner заключается в том, что она подписывается на топик /cmd_vel принимает команды, "прогоняет из через модель" и публикует TF фрейм кинематической или нейросетевой модели.

В ROS-1 это были две ноды
https://github.com/urock/rosbot/blob/develop/rosbot_controller/src/nn_model_runner.py
https://github.com/urock/rosbot/blob/develop/rosbot_controller/src/model_runner.py

Пример запуска описан вот тут  в разделе "Визуализация моделей - кинематическая и нейросетевая"
https://github.com/urock/rosbot/blob/develop/docs/logger.md

В ROS-2 , предлагаю чтобы это была одна нода, но у которой могу быть разные параметры, то есть режим работы:
* кинематическая модель
* нейросетевая модель 

 для этих режимов работы также настраиваются параметры, например частота публикации, имена фреймов (обсудим по ходу выполнения)

**Comment by CI314X** [comment]
Done.

**Comment by CI314X** [comment]
Комментарии:
1) Нейросетевая модель не проверена на весах, отклабированных на ROS2.
2) Возможно нужен лаунчен для одновременного запуска двух нод из одного лаунчера.

**Comment by CI314X** [comment]
История действия:
1) Создан класс с нодой, основной параметр которой - выбор кинематической либо нейросетевой модели.
2) Можно настраивать частоту публикации, путь к весам нейронной модели, имя топика, из которого читаются скорости, имя родительского фрейма (odom)
3) Программа с заданной частотой обновляет скоростное состояние робота, вычисляет его предполагаемое местоположение, и посылает эту информацию в tf фрейм ("kinematic_model_link" или "nn_model_link")
